/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    algoritmosSidebar: [
        {
            type: 'autogenerated',
            dirName: '.', // Generate sidebar from the docs folder structure
        },
    ],
};

module.exports = sidebars;
